version: "3"

services:
  web:
    container_name: railsMVC-rails
    build: .
    command:
      - bash
      - -c
      - |
        rails db:create
        rails db:migrate
        rm -f tmp/pids/server.pid
        bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    container_name: railsMVC-postgresql
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
