default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: railsMVC-postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RailsMVC_development

test:
  <<: *default
  database: RailsMVC_test

production:
  <<: *default
  database: RailsMVC_production
  username: RailsMVC
  password: <%= ENV["RAILSMVC_DATABASE_PASSWORD"] %>
